### ISSUE TITLE
small question

### ISSUE THREAD

**Issue by dutchsing009** [SJTMusicTeam/Muskits#114]
Hello how are you !! very nice team you have here, you guys are making Unbelievable stuff and amazing projects !!
I wanted to ask a question about will you guys fully implement Visingerr like a full implementation with working code and the same results or near as the demo ( as if you want to do that you will have to build it upon vits as it is the same architecture and then modify it) , and if yes is there a date , I saw you saying it will be this month , and that you may change your priorities and take requests and suggestions , so yeah it will be very nice if you started by implementing that paper as it has the best results out of everything (begansing , diffsingerr and hifisingerr) 

Thank you in advance 
and feel free to close the issue upon answering ;)

**Comment by dutchsing009** [comment]
also by full implementation i mean where you can train your own custom model on your own custom data , thanks !!!

**Comment by ftshijt** [comment]
Thanks for your following-up to our project. The implementation of VISinger is definitely on our action item. For now, our first priority is to merge the Muskits into [ESPnet](https://github.com/espnet/espnet) as ESPnet-Muskits, from where we can direct have access to many important modules there (as we already have VITS and many other TTS variants in ESPnet now).

We initially anticipate the implementation will be finished by end of June, but it turns out to be a bit difficult as many of our members are busy other schedules. In general, our plan is delayed by one month.

Meanwhile, as we are heading to improve the design during the merging, we are open to comments and suggestions as well. Please let us know if you have any advice to the project. Many thanks!
