### ISSUE TITLE
is xiaoice pretrain models trained by world feat?

### ISSUE THREAD

**Issue by 11721206** [SJTMusicTeam/Muskits#118]
hello， when I analysis code to find world feat not used in code？I want to confirm that wav->sp->mgc(60) has been done in this repo? and the residual connection in xiaoice has been done in this repo?  thank you

**Comment by ftshijt** [comment]
Thanks for your interest in the toolkits. We use log-mel spectrogram features instead of world feature here. The feature is extrated on-the-fly at https://github.com/SJTMusicTeam/Muskits/blob/main/muskit/svs/feats_extract/log_mel_fbank.py

To get a compatible vocoder, you can use vocoder trained at https://github.com/kan-bayashi/ParallelWaveGAN (we have also published several vocoders for our recipes [there](https://github.com/kan-bayashi/ParallelWaveGAN#results))

**Comment by ftshijt** [comment]
Given that we do not condition on explicit pitch information for the vocoder, we do not take the residual connection for the pitch as in original Xiaoice paper
